# Generated by Django 4.2.5 on 2024-05-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japtuneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
